name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - python=3.9
  - requests
  - selenium
  - jupyterlab-lsp
  - jedi-language-server
  - nodejs
  - pyautogui
  - pyinstaller
  - pip:
    - spacy
    - ipykernel
    - scipy
    - scikit-learn
    - thinc
    - mitosheet3

